export const syllabusData = [
  {
    id: "quant",
    subject: "Quantitative Aptitude",
    icon: "calculator",
    color: "amber",
    description: "Scribe of Numbers & Formulae",
    topics: [
      "Number System",
      "Simplification",
      "Percentage",
      "Ratio & Proportion",
      "Average",
      "Profit & Loss",
      "Time & Work",
      "Time, Speed & Distance",
      "Algebra",
      "Geometry",
      "Mensuration",
      "Trigonometry",
      "Statistics",
      "Data Interpretation",
      "Partnership",
      "Mixture & Alligation",
      "Simple Interest",
      "Compound Interest",
      "Discount",
      "Pipes & Cisterns",
      "Boats & Streams",
      "Ages",
      "Coordinate Geometry"
    ]
  },
  {
    id: "english",
    subject: "English Language",
    icon: "book-open",
    color: "sky",
    description: "Sovereign Rhetoric & Spellcraft",
    topics: [
      "Spotting Errors",
      "Fill in the Blanks",
      "Synonyms & Antonyms",
      "Spelling & Detecting Mis-spelled Words",
      "Idioms & Phrases",
      "One Word Substitution",
      "Sentence Improvement",
      "Active & Passive Voice",
      "Direct & Indirect Speech",
      "Shuffling of Sentence Parts",
      "Shuffling of Sentences in a Passage",
      "Cloze Passage",
      "Comprehension Passage",
      "Vocabulary Mastery",
      "Sentence Completion",
      "Phrase Replacement",
      "Grammar"
    ]
  },
  {
    id: "reasoning",
    subject: "General Intelligence & Reasoning",
    icon: "brain",
    color: "indigo",
    description: "Mental Labyrinth & Logic Trials",
    topics: [
      "Semantic Analogy",
      "Symbolic/Number Analogy",
      "Figural Analogy",
      "Semantic Classification",
      "Symbolic/Number Classification",
      "Figural Classification",
      "Semantic Series",
      "Number Series",
      "Figural Series",
      "Problem Solving & Word Building",
      "Coding and Decoding",
      "Venn Diagrams",
      "Drawing Inferences",
      "Paper Folding & Cutting",
      "Syllogistic Reasoning",
      "Statement & Conclusion",
      "Embedded Figures",
      "Blood Relations",
      "Direction Sense",
      "Alphabet Test",
      "Ranking & Order",
      "Seating Arrangement",
      "Puzzle",
      "Mirror Images",
      "Water Images",
      "Dice",
      "Cube & Cuboid",
      "Counting Figures",
      "Non-Verbal Reasoning",
      "Matrix",
      "Calendar",
      "Clock"
    ]
  },
  {
    id: "awareness",
    subject: "General Awareness",
    icon: "globe",
    color: "emerald",
    description: "Empire Chronicles & Global Lore",
    topics: [
      "History of India",
      "Geography of India & World",
      "Indian Polity & Constitution",
      "Indian Economy",
      "General Science (Physics, Chemistry, Biology)",
      "Scientific Research & Technology",
      "National & International Current Affairs",
      "Books & Authors",
      "Sports & Trophies",
      "Important Schemes & Policies",
      "Static GK (Dance, Art, Culture)",
      "Days, Events & Abbreviations",
      "Honors, Awards & Laurels",
      "Environment & Ecology",
      "Art & Culture",
      "Important Days",
      "Organizations & Headquarters",
      "Countries, Capitals & Currencies",
      "Important Government Institutions",
      "Census & Demographics"
    ]
  }
];
